### ISSUE TITLE
Possibility of using file handle without creating ownership?

### ISSUE THREAD

**Issue by schveiguy** [MartinNowak/io#7]
In iopipe I have a bool when creating a stream object:

```D
this(int fd, bool closeOnDestroy = true)
```

Which tells the object whether or not to close the fd when the object is destroyed.

For things like `stdin` and `stdout`, this is almost necessary, as you don't want to close them just because you are done using them, other things may want to use them that *aren't* D.

But I see no way to duplicate this functionality if iopipe switched to using this library. Thoughts?

**Comment by MartinNowak** [comment]
@schveiguy 
Simply clone file descriptors/handles. I'm a bit wary with providing such runtime switches regarding safety and avoiding leaks.
A problem is that the fixed file descriptors (0, 1, 2) cannot be cloned at compile time, so you couldn't statically create a stdout File. But this is already true due to the switchable driver architecture as well, so it might not matter too much.

**Comment by schveiguy** [comment]
> Simply clone file descriptors/handles

This is a possibility, I'm not familiar with the mechanisms are in Windows that allow this, but seems they [are present](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724251(v=vs.85).aspx).

It would be good, however, to abstract this from the OS differences, as it definitely is something that is required, especially for the standard handles. Perhaps a `cloneFile` function in the driver, which accepts a descriptor/handle (not an `IO`, as that would require ownership again!).

One aspect to be wary of is the cost of using the OS to clone something that you use fleetingly.

> I'm a bit wary with providing such runtime switches regarding safety and avoiding leaks.

The only time you do this is when the user is providing the file descriptor/handle. Files that are opened via the `std.io` drivers should be managed without question. It follows normal lifetime principles that if `std.io` didn't allocate it, then we probably shouldn't be destroying it (unless requested).

Note that in the old `iopipe` stream class, there was no option to set `closeOnDestroy` to false when `iopipe` was opening the file descriptor. Only when you passed in the descriptor could you set this flag. https://github.com/schveiguy/iopipe/blob/b2ef75b9eaefffb0abb8a828f67c200be964bb73/source/iopipe/stream.d#L156

> so you couldn't statically create a stdout File.

I don't think you need to do this during compile time, or even at program startup. Phobos gets away with it since it uses libc's streams as implementation. In our case, it needs to be opt-in.

**Comment by MartinNowak** [comment]
We might also add magic pointer values as static stdin/stdout/stderr values, so that the drivers can use 0/1/2 instead. The problem with cloning is that stdin can be moved to a different file in a process and std.io's stdin should reflect that as well.

If we don't do it statically and pass the raw handles everytime that implied allocating&deallocating a slot in the driver for every usage.

**Comment by schveiguy** [comment]
Using the std handles is still kind of a different issue, which is why I opened #14 as well.

What I'm talking about is, when a std.io handle is destroyed, it always closes the handle/file descriptor. This is not compatible with using any other libraries where we may want to borrow the file descriptor temporarily.

Indeed the standard handles are a specific case, we don't want to close them, and every io library out there defines its own way to use them. std.io shouldn't interfere with `printf` just because you wanted to open stdout to print a string or something.

**Comment by WebFreak001** [comment]
can be closed because of v0.3.0?
